version: "3"
services:
  backend:
    image: production_system
    container_name: "productionsystem"
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - ./ProductionSystem:/code/ProductionSystem
    command: "python manage.py runserver 0.0.0.0:8000"
